raise Exception("This is a test collection error")

def test_ok():
    ...
